[[dsl-symboltable]]

== Symboltable
_Symboltable_ is a relatively vague concept of representing various
internals of a symbol information during a translation of an language
into an internal representation of a language itself. It is vague
concept because it is essentially a simple repository or a data
structure not really based on any real world specification.

[quote, wiki]
____
Symbol table is a data structure used by a language translator such as
a compiler or interpreter, where each identifier (a.k.a. symbol) in
a program's source code is associated with information relating to its
declaration or appearance in the source. Symbol table stores the
information related about the symbol.
____

Most of a time language parsers and lexer really don't care about symbol
information as it really is not their responsibility. For example things
done natively in <<dsl-antlr>> would not be aware of any cross referencing
symbols and if one needs to have this information, one way to do it
is through custom symbol tables. Providing a generic custom table
implementation is one way how _Spring DSL_ can help with these concepts.

include::dsl-symboltable-default.adoc[]

